/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiCharactersRouteImport } from './routes/api/characters'
import { Route as ApiMessagesRouteImport } from './routes/api/messages'
import { Route as ApiCharactersUploadRouteImport } from './routes/api/characters/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCharactersRoute = ApiCharactersRouteImport.update({
  id: '/api/characters',
  path: '/api/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesRoute = ApiMessagesRouteImport.update({
  id: '/api/messages',
  path: '/api/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCharactersUploadRoute = ApiCharactersUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ApiCharactersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/characters': typeof ApiCharactersRouteWithChildren
  '/api/messages': typeof ApiMessagesRoute
  '/api/characters/upload': typeof ApiCharactersUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/characters': typeof ApiCharactersRouteWithChildren
  '/api/messages': typeof ApiMessagesRoute
  '/api/characters/upload': typeof ApiCharactersUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/characters': typeof ApiCharactersRouteWithChildren
  '/api/messages': typeof ApiMessagesRoute
  '/api/characters/upload': typeof ApiCharactersUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth'
    | '/api/characters'
    | '/api/messages'
    | '/api/characters/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth'
    | '/api/characters'
    | '/api/messages'
    | '/api/characters/upload'
  id:
    | '__root__'
    | '/'
    | '/api/auth'
    | '/api/characters'
    | '/api/messages'
    | '/api/characters/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiCharactersRoute: typeof ApiCharactersRouteWithChildren
  ApiMessagesRoute: typeof ApiMessagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/characters': {
      id: '/api/characters'
      path: '/api/characters'
      fullPath: '/api/characters'
      preLoaderRoute: typeof ApiCharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages': {
      id: '/api/messages'
      path: '/api/messages'
      fullPath: '/api/messages'
      preLoaderRoute: typeof ApiMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/characters/upload': {
      id: '/api/characters/upload'
      path: '/upload'
      fullPath: '/api/characters/upload'
      preLoaderRoute: typeof ApiCharactersUploadRouteImport
      parentRoute: typeof ApiCharactersRoute
    }
  }
}

interface ApiCharactersRouteChildren {
  ApiCharactersUploadRoute: typeof ApiCharactersUploadRoute
}

const ApiCharactersRouteChildren: ApiCharactersRouteChildren = {
  ApiCharactersUploadRoute: ApiCharactersUploadRoute,
}

const ApiCharactersRouteWithChildren = ApiCharactersRoute._addFileChildren(
  ApiCharactersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiCharactersRoute: ApiCharactersRouteWithChildren,
  ApiMessagesRoute: ApiMessagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
